### ISSUE TITLE
AssertionError: You should specify the folder of your dataset

### ISSUE THREAD

**Issue by liushuping0528** [xfflzl/CIM-CIL#2]
How to specify the training and test sets of food-101,
```python
def download_data(self):
        assert 0,"You should specify the folder of your dataset"
        train_dir = 'YOUR DATASET TRAIN DIR'
        test_dir = 'YOUR DATASET TEST DIR'
```
The specified training and test set folders were not found in the food-101 dataset, so how should this train_dir and test_dir be specified?

**Comment by xfflzl** [comment]
Hi, the raw `food-101` dataset is not splitted into training and testing parts. Please follow the meta files, e.g., `meta/train.txt` and `meta/test.txt` to split the images into corresponding folders.
