### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './exps/finetune.json' I can't find this path './exps/finetune.json'

### ISSUE THREAD

**Issue by BLACKJACK0711** [xfflzl/CIM-CIL#3]

**Comment by xfflzl** [comment]
Thanks for your interest in our work! Please run `main.py` with setting `config` argument, or `config` argument is set to `'./exps/finetune.json'` by default, which is not available in this repo. So the correct command is `python main.py --config cim-<YOUR DATASET>.json`.
