### ISSUE TITLE
“IndexError: Target 276 is out of bounds”.When faced with this problem, how do I go about finding the fully connected layer and making changes

### ISSUE THREAD

**Issue by BLACKJACK0711** [xfflzl/CIM-CIL#5]

**Comment by xfflzl** [comment]
Thanks for your interest in our work!

The fully connected layers are set here.
https://github.com/xfflzl/CIM-CIL/blob/b45914a27323182dea5053e381ef3dbe79b18cf8/utils/inc_net.py#L411

But I guess your problem can be addressed by adjusting the configuration file. Specifically, please set proper numbers for `init_cls` and `increment` in the .json file. These two items are used to control how many classes comes in the first phase and subsequent phases.
